-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_username_key`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `registration` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `guardian1_name` VARCHAR(191) NOT NULL,
    `guardian1_contact_no` VARCHAR(191) NOT NULL,
    `guardian1_id_type` VARCHAR(191) NOT NULL,
    `guardian1_ic` VARCHAR(191) NULL,
    `guardian1_passport` VARCHAR(191) NULL,
    `guardian1_relationship` VARCHAR(191) NOT NULL,
    `guardian2_name` VARCHAR(191) NOT NULL,
    `guardian2_contact_no` VARCHAR(191) NOT NULL,
    `guardian2_id_type` VARCHAR(191) NOT NULL,
    `guardian2_ic` VARCHAR(191) NULL,
    `guardian2_passport` VARCHAR(191) NULL,
    `guardian2_relationship` VARCHAR(191) NOT NULL,
    `main_contact` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `emergency_name` VARCHAR(191) NOT NULL,
    `emergency_contact_no` VARCHAR(191) NOT NULL,
    `emergency_relationship` VARCHAR(191) NOT NULL,
    `add_adult_amount` INTEGER NOT NULL,
    `add_adult1_name` VARCHAR(191) NULL,
    `add_adult1_contact_no` VARCHAR(191) NULL,
    `add_adult1_ic` VARCHAR(191) NULL,
    `add_adult1_relationship` VARCHAR(191) NULL,
    `add_adult2_name` VARCHAR(191) NULL,
    `add_adult2_contact_no` VARCHAR(191) NULL,
    `add_adult2_ic` VARCHAR(191) NULL,
    `add_adult2_relationship` VARCHAR(191) NULL,
    `add_adult3_name` VARCHAR(191) NULL,
    `add_adult3_contact_no` VARCHAR(191) NULL,
    `add_adult3_ic` VARCHAR(191) NULL,
    `add_adult3_relationship` VARCHAR(191) NULL,
    `children_amount` INTEGER NOT NULL,
    `child1_name` VARCHAR(191) NOT NULL,
    `child1_nickname` VARCHAR(191) NOT NULL,
    `child1_gender` VARCHAR(191) NOT NULL,
    `child1_age` INTEGER NOT NULL,
    `child1_dob` DATETIME(3) NULL,
    `child1_id_type` VARCHAR(191) NOT NULL,
    `child1_ic` VARCHAR(191) NULL,
    `child1_passport` VARCHAR(191) NULL,
    `child2_name` VARCHAR(191) NULL,
    `child2_nickname` VARCHAR(191) NULL,
    `child2_gender` VARCHAR(191) NULL,
    `child2_age` INTEGER NULL,
    `child2_dob` DATETIME(3) NULL,
    `child2_id_type` VARCHAR(191) NULL,
    `child2_ic` VARCHAR(191) NULL,
    `child2_passport` VARCHAR(191) NULL,
    `child3_name` VARCHAR(191) NULL,
    `child3_nickname` VARCHAR(191) NULL,
    `child3_gender` VARCHAR(191) NULL,
    `child3_age` INTEGER NULL,
    `child3_dob` DATETIME(3) NULL,
    `child3_id_type` VARCHAR(191) NULL,
    `child3_ic` VARCHAR(191) NULL,
    `child3_passport` VARCHAR(191) NULL,
    `add_child_amount` INTEGER NOT NULL,
    `add_child1_name` VARCHAR(191) NULL,
    `add_child1_nickname` VARCHAR(191) NULL,
    `add_child1_gender` VARCHAR(191) NULL,
    `add_child1_age` INTEGER NULL,
    `add_child1_dob` DATETIME(3) NULL,
    `add_child1_id_type` VARCHAR(191) NULL,
    `add_child1_ic` VARCHAR(191) NULL,
    `add_child1_passport` VARCHAR(191) NULL,
    `add_child2_name` VARCHAR(191) NULL,
    `add_child2_nickname` VARCHAR(191) NULL,
    `add_child2_gender` VARCHAR(191) NULL,
    `add_child2_age` INTEGER NULL,
    `add_child2_dob` DATETIME(3) NULL,
    `add_child2_id_type` VARCHAR(191) NULL,
    `add_child2_ic` VARCHAR(191) NULL,
    `add_child2_passport` VARCHAR(191) NULL,
    `add_child3_name` VARCHAR(191) NULL,
    `add_child3_nickname` VARCHAR(191) NULL,
    `add_child3_gender` VARCHAR(191) NULL,
    `add_child3_age` INTEGER NULL,
    `add_child3_dob` DATETIME(3) NULL,
    `add_child3_id_type` VARCHAR(191) NULL,
    `add_child3_ic` VARCHAR(191) NULL,
    `add_child3_passport` VARCHAR(191) NULL,
    `package_default` INTEGER NOT NULL,
    `addon_children_below_4` INTEGER NOT NULL,
    `addon_children_5_to_10` INTEGER NOT NULL,
    `addon_above_10` INTEGER NOT NULL,
    `heard_info` VARCHAR(191) NOT NULL,
    `heard_info_others` VARCHAR(191) NULL,
    `heard_info_scode` VARCHAR(191) NULL,
    `payment_image` VARCHAR(191) NULL,
    `total_amount` DECIMAL(65, 30) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
