declare module "registration" {
  interface Registration {
    id: number;
    guardian1_name: string;
    guardian1_contact_no: string;
    guardian1_id_type: string;
    guardian1_ic?: string | null;
    guardian1_passport?: string | null;
    guardian1_relationship: string;
    guardian2_name: string;
    guardian2_contact_no: string;
    guardian2_id_type: string;
    guardian2_ic?: string | null;
    guardian2_passport?: string | null;
    guardian2_relationship: string;
    main_contact: string;
    address: string;
    email: string;
    emergency_name: string;
    emergency_contact_no: string;
    emergency_relationship: string;
    add_adult_amount: number;
    add_adult1_name?: string;
    add_adult1_contact_no?: string;
    add_adult1_ic?: string | null;
    add_adult1_relationship?: string;
    add_adult2_name?: string;
    add_adult2_contact_no?: string;
    add_adult2_ic?: string | null;
    add_adult2_relationship?: string;
    add_adult3_name?: string;
    add_adult3_contact_no?: string;
    add_adult3_ic?: string | null;
    add_adult3_relationship?: string;
    children_amount: number;
    child1_name: string;
    child1_nickname: string;
    child1_gender: string;
    child1_age: number;
    child1_dob?: string | null;
    child1_id_type: string;
    child1_ic?: string | null;
    child1_passport?: string | null;
    child2_name?: string;
    child2_nickname?: string;
    child2_gender?: string;
    child2_age?: number;
    child2_dob?: string | null;
    child2_id_type?: string;
    child2_ic?: string | null;
    child2_passport?: string | null;
    child3_name?: string;
    child3_nickname?: string;
    child3_gender?: string;
    child3_age?: number;
    child3_dob?: string | null;
    child3_id_type?: string;
    child3_ic?: string | null;
    child3_passport?: string | null;
    add_child_amount?: number;
    add_child1_name?: string;
    add_child1_nickname?: string;
    add_child1_gender?: string;
    add_child1_age?: number;
    add_child1_dob?: string | null;
    add_child1_id_type?: string;
    add_child1_ic?: string | null;
    add_child1_passport?: string | null;
    add_child2_name?: string;
    add_child2_nickname?: string;
    add_child2_gender?: string;
    add_child2_age?: number;
    add_child2_dob?: string | null;
    add_child2_id_type?: string;
    add_child2_ic?: string | null;
    add_child2_passport?: string | null;
    add_child3_name?: string;
    add_child3_nickname?: string;
    add_child3_gender?: string;
    add_child3_age?: number;
    add_child3_dob?: string | null;
    add_child3_id_type?: string;
    add_child3_ic?: string | null;
    add_child3_passport?: string | null;
    package_default: number;
    addon_children_below_4: number;
    addon_children_5_to_10: number;
    addon_above_10: number;
    heard_info: string;
    heard_info_others?: string;
    heard_info_scode?: string;
    payment_image?: string;
    total_amount: string;
    created_at: Date;
    updated_at: Date;
  }
}